module.exports = {
  OTP_EXPIRY_MINUTES: 5,
  OTP_RESEND_LIMIT: 3,
  OTP_VERIFY_ATTEMPT_LIMIT: 5,
  OTP_RESEND_COOLDOWN_SECONDS: 30,
  PENDING_SIGNUP_TTL_MINUTES: 30,
  PASSWORD_RESET_TTL_MINUTES: 15,
};
